apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: dev
type: Opaque
stringData:
  USER_NAME: "admin"
  PASSWORD: "letmein"
  POSTGRES_USERNAME: "user"
  POSTGRES_PASSWORD: "letmein"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_ID: "contact.aivisionworld@gmail.com"
  EMAIL_PASSWORD: "ngkcazondlvvvfsg"