apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
  namespace: dev
  labels:
    app: discovery
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - discovery
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: discovery
          image: discoveryservice:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: discovery-config
                  key: SERVER_PORT
            - name: ACTIVE_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: discovery-config
                  key: ACTIVE_PROFILE
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: discovery-config
                  key: EUREKA_HOST
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: discovery-secret
                  key: USER_NAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discovery-secret
                  key: PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: discovery-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: discovery-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: discovery-config
                  key: POSTGRES_DATABASE
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discovery-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discovery-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8761