apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: dev
  labels:
    app: user
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - user
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: user
          image: userservice:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SERVER_PORT
            - name: ACTIVE_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: ACTIVE_PROFILE
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: EUREKA_HOST
            - name: EUREKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: EUREKA_PORT
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: USER_NAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: POSTGRES_DATABASE
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: POSTGRES_PASSWORD
            - name: KAFKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: KAFKA_SERVER_URL
            - name: JWKS_URI
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: JWKS_URI
          ports:
            - containerPort: 8081