apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: authorization
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30094