apiVersion: v1
kind: Secret
metadata:
  name: ticket-secret
  namespace: dev
type: Opaque
stringData:
  USER_NAME: "admin"
  PASSWORD: "letmein"
  POSTGRES_USERNAME: "user"
  POSTGRES_PASSWORD: "letmein"